var Queries = [
  {name: "Lion",
  title: "large cat native to Africa and Asia",
  img: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/73/Lion_waiting_in_Namibia.jpg/50px-Lion_waiting_in_Namibia.jpg"},
  {name: "Lionel Messi",  
  title: "Argentine footballer",
  img: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c1/Lionel_Messi_20180626.jpg/35px-Lionel_Messi_20180626.jpg" },
  {name: "Lionsgate",
  title: "American entertainment company",
  },
  {name: "Lion Air Flight 610",
  title: "2018 aircraft crash in the Java Sear , Indonesia , killing 189",
  img:"https://upload.wikimedia.org/wikipedia/commons/thumb/d/d6/Lion_Air_Boeing_737-MAX8_PK-LQP.jpg/50px-Lion_Air_Boeing_737-MAX8_PK-LQP.jpg"},
  {name: "Lionel Richie",
  title: "American entertainer",
  img:"https://upload.wikimedia.org/wikipedia/commons/thumb/8/89/Lionel_Richie_in_2017.jpg/37px-Lionel_Richie_in_2017.jpg"},
  {name: "Lions Clubs International",
  title: "International service organization base in the US",
 },
  {name: "Lion dance",
  title:"Lion dance",
  img:"https://upload.wikimedia.org/wikipedia/commons/thumb/d/d0/Chinese_New_Year_Lion_Dance.jpg/44px-Chinese_New_Year_Lion_Dance.jpg"
  },
  
  {name: "Lion Capital of Ashoka",
  title:"Lion Capital of Ashoka",
  img:"https://upload.wikimedia.org/wikipedia/commons/thumb/3/38/Sarnath_capital.jpg/28px-Sarnath_capital.jpg"},
  {name: "Lion and Sun",
  title:"Lion and Sun",
  img:"https://upload.wikimedia.org/wikipedia/commons/thumb/9/91/Lion_and_Sun_Emblem_of_Persia.svg/50px-Lion_and_Sun_Emblem_of_Persia.svg.png"}
  ];